### ISSUE TITLE
semaphore API is skipped when tests are disabled

### ISSUE THREAD

**Issue by alex-tee** [drobilla/zix#3]
I get the following when using as a subproject with tests disabled:
```
zix| Dependency threads skipped: feature tests disabled
```

This seems to be the cause

```meson
thread_dep = dependency('threads', required: get_option('tests'))
```

**Comment by drobilla** [comment]
Oops.  This ability of "required" is often handy, but also confusing because it's called "required" and all...

Fixed in 124355e, thanks.
