### ISSUE TITLE
Invalid #include when linking and compiling.

### ISSUE THREAD

**Issue by Stazed** [drobilla/zix#4]
Getting a number of these errors when trying to link and build with the library installed:

     `/usr/include/zix-0/zix/ring.h:7:10: fatal error: zix/allocator.h: No such file or directory
       7 | #include "zix/allocator.h" `

I was able to get it to work by removing the  leading "zix/" for the various files:

      `#include "zix/allocator.h"  >> #include "allocator.h"`

It seems the #include files are in the same directory and the "zix/" is confusing things.

Occurs on Manjaro, Ubuntu Studio, OpenSuse Tumbleweed and Fedora 36.

Built and installed from this repository as well as used the arch/aur package with same result.

Thanks.

**Comment by drobilla** [comment]
The include lines are correct.  Your compiler flags aren't.

> Getting a number of these errors when trying to link and build with the library installed:

When trying to link and build what?  How?  What command does this error come from?

**Comment by Stazed** [comment]
>When trying to link and build what? How? What command does this error come from?

Attempting to build:

>https://github.com/Stazed/non-mixer-xt.git

Checkout the libzix branch.

Using cmake, it links and occurs when running make.

**Comment by Stazed** [comment]
Apologies!!!

Just found my screwup.

I think I need to take a break from programming!

Closing.
